recipe: default.v1
assistant_id: warm-canal
language: en
pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: openai-gpt-5-1
  flow_retrieval:
    embeddings:
      model_group: openai-text-embedding-3-large
policies:
- name: FlowPolicy
