recipe: default.v1
language: en
pipeline:
- name: NLUCommandAdapter
- name: CompactLLMCommandGenerator
  llm:
    model_group: openai-gpt-4o
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
assistant_id: action-error-handling
